
server.port=${PORT:8181}

spring.h2.console.enabled=true
spring.jpa.show-sql = true

spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create


app.security.jwt.secretKey=${APP_SECURITY_JWT_SECRET_KEY:mySecretKey}
app.security.jwt.expirationTime=${APP_SECURITY_JWT_EXPIRATION_TIME:86400} 

app.development.module=Evaluacion Tecnica
app.development.process=Registro Usuario - Generacion Token
app.development.author=Cesar Castillo
app.development.version=1.0.0
 